# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
            AppBundle\Entity\User:
                algorithm: bcrypt
                cost: 12

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~

        app_user_provider:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: app_user_provider
            form_login:
                login_path: login
                check_path: login_check
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: logout
                target: /

    access_control:
        # Allow access to the login and logout routes without authentication
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        
        # Require authentication for all other routes
        - { path: ^/, roles: [ROLE_USER, ROLE_ADMIN] }
